# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Inverse
version:      0.02
version_from: lib/Geo/Inverse.pm
installdirs:  site
requires:
    Geo::Constants:                0.02
    Geo::Ellipsoids:               0
    Geo::Functions:                0.02
    strict:                        0
    vars:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
